apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadbot-app-deploy
  namespace: default
  labels:
    app: dadbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dadbot-app
  template:
    metadata:
      labels:
        app: dadbot-app
    spec:
      containers:
      - name: dadbot-app
        image: craigers521/dadbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: dadbot-app
spec:
  type: NodePort
  selector:
    app: dadbot-app
  ports:
  - port: 3000
    targetPort: 3000